### ISSUE TITLE
Cuatro colinas  map not working

### ISSUE THREAD

**Issue by thomas1446** [kk49/deca_website#28]
Hello 
The map Cuatro colinas not show any animals, file is not loaded

(There is no source code for deca_website ?, i(m developer i could help you too ;-) )

**Comment by kk49** [comment]
Typically that can occur if you have not re-entered a map and updated your save files for that reserve. It's all data based so it typically does not take a change to the code to support those changes, just reprocessing the data. I can double check that I have the latest release processed...

I've hesitated on releasing the code (which is a thin set hacked scripts around deca (https://github.com/kk49/deca) ) because it is a mess and geared to my website layout.
